server:
  ssl:
    enabled: false
  port: 8080
application:
  external:
    sync:
      offer-max-years: 1
      audit:
        enabled: true
        response-body: false
    nausys:
      base-url: ${NAUSYS_URL:http://ws.nausys.com}
      username: ${NAUSYS_USERNAME}
      password: ${NAUSYS_PASSWORD}
    mmk:
      base-url: ${MMK_URL:https://www.booking-manager.com/api/v2}
      bearer: ${MMK_TOKEN}
  email:
    from-address: boat4you <no-reply@boat4you.com>
  invites:
    user:
      allow-uninvited-login: false
  test:
    enabled: false
  security:
    jwt:
      secret-key: ${JWT_SIGNATURE_KEY}
spring:
  mail:
    host: ${MAIL_SERVER_HOST}
    port: ${MAIL_SERVER_PORT}
    username: ${MAIL_SERVER_USERNAME}
    password: ${MAIL_SERVER_PASSWORD}
    properties:
      mail:
        test-connection: ${application.email.enabled}
        smtp:
          auth: true
          ssl:
            enable: true
          starttls:
            enable: false
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:boat4you_db}
    username: ${DB_USER:boat4you_app}
    password: ${DB_PASSWORD:boat4you_app}
  flyway:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:boat4you_db}
    user: ${FLYWAY_USER:boat4you_owner}
    password: ${FLYWAY_PASSWORD:boat4you_owner}
    out-of-order: ${FLYWAY_OUT_OF_ORDER:false}
  jpa:
    properties:
      format_sql: false
    show-sql: false
