server:
  host-public: https://localhost:8443
  host-admin-public: https://localhost:8443
#  ssl:
#    enabled: false
#  port: 8443
application:
  external:
    sync:
      offer-max-years: 1
      audit:
        enabled: true
        response-body: false
    nausys:
      base-url: http://ws.nausys.com
      username: rest344@TTTTT
      password: wrpKiCvP
#      username: rest@EURCU
#      password: C93r5cMK
    mmk:
      base-url: https://www.booking-manager.com/api/v2
      bearer: 63d-209555d80590103d19f2b21ab1383c63c218dc31e02d1af3f7016730ee7944c6c34299d4930ad08926db871e290d575465cd9a1bf0858c0b90c1a2552e521e16
  upload:
    max-file-size: 10MB
    max-request-size: 50MB
    directory: /Users/kresimirhorvat/projects/workspace/boat4you_data
  email:
    enabled: false
  stripe:
    enabled: false
  viva:
    enabled: false
  test:
    enabled: true
spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5434}/${DB_NAME:boat4you_db}
    username: ${DB_USER:boat4you_app}
    password: ${DB_PASSWORD:boat4you_app}
  flyway:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5434}/${DB_NAME:boat4you_db}
    user: boat4you_owner
    password: boat4you_owner
    out-of-order: true
  jpa:
    properties:
      format_sql: false
    show-sql: false