package hr.workspace.boat4you.domains.catalouge.enums

enum class CountryIsoEnum(
    val englishName: String,
    val alpha3Code: String,
    val continent: String,
) {
    AF("Afghanistan", "AFG", "Asia"),
    AL("Albania", "ALB", "Europe"),
    DZ("Algeria", "DZA", "Africa"),
    AS("American Samoa", "ASM", "Oceania"),
    AD("Andorra", "AND", "Europe"),
    AO("Angola", "AGO", "Africa"),
    AI("Anguilla", "AIA", "North America"),
    AQ("Antarctica", "ATA", "Antarctica"),
    AG("Antigua and Barbuda", "ATG", "North America"),
    AR("Argentina", "ARG", "South America"),
    AM("Armenia", "ARM", "Asia"),
    AW("Aruba", "ABW", "North America"),
    AU("Australia", "AUS", "Oceania"),
    AT("Austria", "AUT", "Europe"),
    AZ("Azerbaijan", "AZE", "Asia"),
    BS("Bahamas", "BHS", "North America"),
    BH("Bahrain", "BHR", "Asia"),
    BD("Bangladesh", "BGD", "Asia"),
    BB("Barbados", "BRB", "North America"),
    BY("Belarus", "BLR", "Europe"),
    BE("Belgium", "BEL", "Europe"),
    BZ("Belize", "BLZ", "North America"),
    BJ("Benin", "BEN", "Africa"),
    BM("Bermuda", "BMU", "North America"),
    BT("Bhutan", "BTN", "Asia"),
    BO("Bolivia", "BOL", "South America"),
    BQ("Caribbean Netherlands", "BES", "North America"),
    BA("Bosnia and Herzegovina", "BIH", "Europe"),
    BW("Botswana", "BWA", "Africa"),
    BV("Bouvet Island", "BVT", "Antarctica"),
    BR("Brazil", "BRA", "South America"),
    IO("British Indian Ocean Territory", "IOT", "Asia"),
    BN("Brunei Darussalam", "BRN", "Asia"),
    BG("Bulgaria", "BGR", "Europe"),
    BF("Burkina Faso", "BFA", "Africa"),
    BI("Burundi", "BDI", "Africa"),
    CV("Cabo Verde", "CPV", "Africa"),
    KH("Cambodia", "KHM", "Asia"),
    CM("Cameroon", "CMR", "Africa"),
    CA("Canada", "CAN", "North America"),
    KY("Cayman Islands", "CYM", "North America"),
    CF("Central African Republic", "CAF", "Africa"),
    TD("Chad", "TCD", "Africa"),
    CL("Chile", "CHL", "South America"),
    CN("China", "CHN", "Asia"),
    CX("Christmas Island", "CXR", "Asia"),
    CC("Cocos (Keeling) Islands", "CCK", "Asia"),
    CO("Colombia", "COL", "South America"),
    KM("Comoros", "COM", "Africa"),
    CD("Democratic Republic of the Congo", "COD", "Africa"),
    CG("Congo", "COG", "Africa"),
    CK("Cook Islands", "COK", "Oceania"),
    CR("Costa Rica", "CRI", "North America"),
    HR("Croatia", "HRV", "Europe"),
    CU("Cuba", "CUB", "North America"),
    CW("Curaçao", "CUW", "North America"),
    CY("Cyprus", "CYP", "Europe"),
    CZ("Czechia", "CZE", "Europe"),
    CI("Côte d'Ivoire", "CIV", "Africa"),
    DK("Denmark", "DNK", "Europe"),
    DJ("Djibouti", "DJI", "Africa"),
    DM("Dominica", "DMA", "North America"),
    DO("Dominican Republic", "DOM", "North America"),
    EC("Ecuador", "ECU", "South America"),
    EG("Egypt", "EGY", "Africa"),
    SV("El Salvador", "SLV", "North America"),
    GQ("Equatorial Guinea", "GNQ", "Africa"),
    ER("Eritrea", "ERI", "Africa"),
    EE("Estonia", "EST", "Europe"),
    SZ("Eswatini", "SWZ", "Africa"),
    ET("Ethiopia", "ETH", "Africa"),
    FK("Falkland Islands", "FLK", "South America"),
    FO("Faroe Islands", "FRO", "Europe"),
    FJ("Fiji", "FJI", "Oceania"),
    FI("Finland", "FIN", "Europe"),
    FR("France", "FRA", "Europe"),
    GF("French Guiana", "GUF", "South America"),
    PF("French Polynesia", "PYF", "Oceania"),
    TF("French Southern Territories", "ATF", "Antarctica"),
    GA("Gabon", "GAB", "Africa"),
    GM("Gambia", "GMB", "Africa"),
    GE("Georgia", "GEO", "Asia"),
    DE("Germany", "DEU", "Europe"),
    GH("Ghana", "GHA", "Africa"),
    GI("Gibraltar", "GIB", "Europe"),
    GR("Greece", "GRC", "Europe"),
    GL("Greenland", "GRL", "North America"),
    GD("Grenada", "GRD", "North America"),
    GP("Guadeloupe", "GLP", "North America"),
    GU("Guam", "GUM", "Oceania"),
    GT("Guatemala", "GTM", "North America"),
    GG("Guernsey", "GGY", "Europe"),
    GN("Guinea", "GIN", "Africa"),
    GW("Guinea-Bissau", "GNB", "Africa"),
    GY("Guyana", "GUY", "South America"),
    HT("Haiti", "HTI", "North America"),
    HM("Heard Island and McDonald Islands", "HMD", "Antarctica"),
    VA("Holy See", "VAT", "Europe"),
    HN("Honduras", "HND", "North America"),
    HK("Hong Kong", "HKG", "Asia"),
    HU("Hungary", "HUN", "Europe"),
    IS("Iceland", "ISL", "Europe"),
    IN("India", "IND", "Asia"),
    ID("Indonesia", "IDN", "Asia"),
    IR("Iran", "IRN", "Asia"),
    IQ("Iraq", "IRQ", "Asia"),
    IE("Ireland", "IRL", "Europe"),
    IM("Isle of Man", "IMN", "Europe"),
    IL("Israel", "ISR", "Asia"),
    IT("Italy", "ITA", "Europe"),
    JM("Jamaica", "JAM", "North America"),
    JP("Japan", "JPN", "Asia"),
    JE("Jersey", "JEY", "Europe"),
    JO("Jordan", "JOR", "Asia"),
    KZ("Kazakhstan", "KAZ", "Asia"),
    KE("Kenya", "KEN", "Africa"),
    KI("Kiribati", "KIR", "Oceania"),
    KP("North Korea", "PRK", "Asia"),
    KR("South Korea", "KOR", "Asia"),
    KW("Kuwait", "KWT", "Asia"),
    KG("Kyrgyzstan", "KGZ", "Asia"),
    LA("Lao People's Democratic Republic", "LAO", "Asia"),
    LV("Latvia", "LVA", "Europe"),
    LB("Lebanon", "LBN", "Asia"),
    LS("Lesotho", "LSO", "Africa"),
    LR("Liberia", "LBR", "Africa"),
    LY("Libya", "LBY", "Africa"),
    LI("Liechtenstein", "LIE", "Europe"),
    LT("Lithuania", "LTU", "Europe"),
    LU("Luxembourg", "LUX", "Europe"),
    MO("Macao", "MAC", "Asia"),
    MG("Madagascar", "MDG", "Africa"),
    MW("Malawi", "MWI", "Africa"),
    MY("Malaysia", "MYS", "Asia"),
    MV("Maldives", "MDV", "Asia"),
    ML("Mali", "MLI", "Africa"),
    MT("Malta", "MLT", "Europe"),
    MH("Marshall Islands", "MHL", "Oceania"),
    MQ("Martinique", "MTQ", "North America"),
    MR("Mauritania", "MRT", "Africa"),
    MU("Mauritius", "MUS", "Africa"),
    YT("Mayotte", "MYT", "Africa"),
    MX("Mexico", "MEX", "North America"),
    FM("Micronesia", "FSM", "Oceania"),
    MD("Moldova", "MDA", "Europe"),
    MC("Monaco", "MCO", "Europe"),
    MN("Mongolia", "MNG", "Asia"),
    ME("Montenegro", "MNE", "Europe"),
    MS("Montserrat", "MSR", "North America"),
    MA("Morocco", "MAR", "Africa"),
    MZ("Mozambique", "MOZ", "Africa"),
    MM("Myanmar", "MMR", "Asia"),
    NA("Namibia", "NAM", "Africa"),
    NR("Nauru", "NRU", "Oceania"),
    NP("Nepal", "NPL", "Asia"),
    NL("Netherlands", "NLD", "Europe"),
    NC("New Caledonia", "NCL", "Oceania"),
    NZ("New Zealand", "NZL", "Oceania"),
    NI("Nicaragua", "NIC", "North America"),
    NE("Niger", "NER", "Africa"),
    NG("Nigeria", "NGA", "Africa"),
    NU("Niue", "NIU", "Oceania"),
    NF("Norfolk Island", "NFK", "Oceania"),
    MK("North Macedonia", "MKD", "Europe"),
    MP("Northern Mariana Islands", "MNP", "Oceania"),
    NO("Norway", "NOR", "Europe"),
    OM("Oman", "OMN", "Asia"),
    PK("Pakistan", "PAK", "Asia"),
    PW("Palau", "PLW", "Oceania"),
    PS("Palestine, State of", "PSE", "Asia"),
    PA("Panama", "PAN", "North America"),
    PG("Papua New Guinea", "PNG", "Oceania"),
    PY("Paraguay", "PRY", "South America"),
    PE("Peru", "PER", "South America"),
    PH("Philippines", "PHL", "Asia"),
    PN("Pitcairn", "PCN", "Oceania"),
    PL("Poland", "POL", "Europe"),
    PT("Portugal", "PRT", "Europe"),
    PR("Puerto Rico", "PRI", "North America"),
    QA("Qatar", "QAT", "Asia"),
    RO("Romania", "ROU", "Europe"),
    RU("Russian Federation", "RUS", "Europe"),
    RW("Rwanda", "RWA", "Africa"),
    RE("Réunion", "REU", "Africa"),
    BL("Saint Barthélemy", "BLM", "North America"),
    SH("Saint Helena, Ascension and Tristan da Cunha", "SHN", "Africa"),
    KN("Saint Kitts and Nevis", "KNA", "North America"),
    LC("Saint Lucia", "LCA", "North America"),
    MF("Saint Martin (French part)", "MAF", "North America"),
    PM("Saint Pierre and Miquelon", "SPM", "North America"),
    VC("Saint Vincent and the Grenadines", "VCT", "North America"),
    WS("Samoa", "WSM", "Oceania"),
    SM("San Marino", "SMR", "Europe"),
    ST("Sao Tome and Principe", "STP", "Africa"),
    SA("Saudi Arabia", "SAU", "Asia"),
    SN("Senegal", "SEN", "Africa"),
    RS("Serbia", "SRB", "Europe"),
    SC("Seychelles", "SYC", "Africa"),
    SL("Sierra Leone", "SLE", "Africa"),
    SG("Singapore", "SGP", "Asia"),
    SX("Sint Maarten (Dutch part)", "SXM", "North America"),
    SK("Slovakia", "SVK", "Europe"),
    SI("Slovenia", "SVN", "Europe"),
    SB("Solomon Islands", "SLB", "Oceania"),
    SO("Somalia", "SOM", "Africa"),
    ZA("South Africa", "ZAF", "Africa"),
    GS("South Georgia and the South Sandwich Islands", "SGS", "Antarctica"),
    SS("South Sudan", "SSD", "Africa"),
    ES("Spain", "ESP", "Europe"),
    LK("Sri Lanka", "LKA", "Asia"),
    SD("Sudan", "SDN", "Africa"),
    SR("Suriname", "SUR", "South America"),
    SJ("Svalbard and Jan Mayen", "SJM", "Europe"),
    SE("Sweden", "SWE", "Europe"),
    CH("Switzerland", "CHE", "Europe"),
    SY("Syrian Arab Republic", "SYR", "Asia"),
    TW("Taiwan", "TWN", "Asia"),
    TJ("Tajikistan", "TJK", "Asia"),
    TZ("Tanzania, the United Republic of", "TZA", "Africa"),
    TH("Thailand", "THA", "Asia"),
    TL("Timor-Leste", "TLS", "Asia"),
    TG("Togo", "TGO", "Africa"),
    TK("Tokelau", "TKL", "Oceania"),
    TO("Tonga", "TON", "Oceania"),
    TT("Trinidad and Tobago", "TTO", "North America"),
    TN("Tunisia", "TUN", "Africa"),
    TM("Turkmenistan", "TKM", "Asia"),
    TC("Turks and Caicos Islands", "TCA", "North America"),
    TV("Tuvalu", "TUV", "Oceania"),
    TR("Türkiye", "TUR", "Europe"),
    UG("Uganda", "UGA", "Africa"),
    UA("Ukraine", "UKR", "Europe"),
    AE("United Arab Emirates", "ARE", "Asia"),
    GB("United Kingdom of Great Britain and Northern Ireland", "GBR", "Europe"),
    UM("United States Minor Outlying Islands", "UMI", "Oceania"),
    US("United States of America", "USA", "North America"),
    UY("Uruguay", "URY", "South America"),
    UZ("Uzbekistan", "UZB", "Asia"),
    VU("Vanuatu", "VUT", "Oceania"),
    VE("Venezuela", "VEN", "South America"),
    VN("Viet Nam", "VNM", "Asia"),
    VG("Virgin Islands (British)", "VGB", "North America"),
    VI("Virgin Islands (U.S.)", "VIR", "North America"),
    WF("Wallis and Futuna", "WLF", "Oceania"),
    EH("Western Sahara", "ESH", "Africa"),
    YE("Yemen", "YEM", "Asia"),
    ZM("Zambia", "ZMB", "Africa"),
    ZW("Zimbabwe", "ZWE", "Africa"),
    AX("Åland Islands", "ALA", "Europe"),
    AN("Netherlands Antilles", "ANT", "North America"),
    XK("Kosovo", "XKX", "Europe"),
    ;

    companion object {
        fun getValue(string: String): CountryIsoEnum? {
            return fromEnumString(string) ?: fromEnglishName(string) ?: fromAlpha3Code(string)
        }

        private fun fromEnglishName(englishName: String): CountryIsoEnum? {
            return CountryIsoEnum.entries.find { it.englishName.equals(englishName, ignoreCase = true) }
        }

        private fun fromAlpha3Code(alpha3Code: String): CountryIsoEnum? {
            return CountryIsoEnum.entries.find { it.alpha3Code.equals(alpha3Code, ignoreCase = true) }
        }

        private fun fromEnumString(enumString: String): CountryIsoEnum? {
            return try {
                enumValueOf<CountryIsoEnum>(enumString)
            } catch (e: IllegalArgumentException) {
                null
            }
        }
    }
}
