INSERT INTO extras (id, name, label_code, match_keys, filter_order)
VALUES (1, 'Skipper', 'skipper', 'skipper, case-substring:Skipper, not:charter pack, not:transit log, not:comfort pack, not:additional fee', 1),
       (2, 'Hostess', 'hostess', 'hostess, not:charter pack, not:transit log, not:comfort pack', 2),
       (3, 'Cook/Chef', 'cook', 'cook, chef, not:charter pack, not:transit log, not:comfort pack', null),
       (4, 'Towels', 'towels', 'towels, not:charter pack, not:transit log, not:comfort pack', null),
       (5, 'Pets onboard', 'pets-onboard', 'pets,pets on board, not:charter pack, not:transit log, not:comfort pack', null),
       (6, 'Safety net', 'safety-net', 'railing net,safety net,railing net safety, not:charter pack, not:transit log, not:comfort pack', 3),
       (7, 'Beach towels', 'beach-towels', 'beach towels, not:charter pack, not:transit log, not:comfort pack', 4),
       (8, 'Dinghy outboard engine', 'dinghy-outboard-engine', 'dinghy,dinghy outboard engine,outboard engine, not:transit log, not:comfort pack', 6),
       (9, 'Stand up paddle (SUP)', 'stand-up-paddle-SUP', 'case-substring:SUP, full-match:SUP, case:SUP, stand up paddle, not:charter pack, not:transit log, not:comfort pack', 5),
       (10, 'Kayak', 'kayak', 'kayak, not:charter pack, not:transit log, not:comfort pack', 7),
       (11, 'Tourist tax', 'tourist-tax', 'tourist tax, not:charter pack, not:transit log, not:comfort pack', null),
       (12, 'Transit log', 'transit-log', 'charter pack,final cleaning,transit log', null),
       (13, 'Refundable security deposit', 'refundable-security-deposit', 'refundable security deposit, not:charter pack, not:transit log, not:comfort pack', null),
       (14, 'Deposit insurance', 'deposit-insurance', 'deposit insurance, not:charter pack, not:transit log, not:comfort pack', null),
       (15, 'Early boarding / Early Check-in', 'early-boarding', 'token-match:early check-in, token-match:early boarding, not:charter pack, not:transit log, not:comfort pack', null),
       (16, 'Late boarding / Late Check-in', 'late-boarding', 'token-match:late check-in, token-match:late boarding, not:charter pack, not:transit log, not:comfort pack', null),
       (17, 'Wi-Fi / Internet Pack', 'wi-fi', 'wi-fi, wifi, case-substring:WIFI, case-substring:WI-FI, not:charter pack, not:transit log, not:comfort pack', null),
       (18, 'Vip Pack', 'vip-pack', 'vip pack, not:charter pack, not:transit log, not:comfort pack', null),
       (19, 'Grill/Barbecue/Plancha', 'grill', 'grill, barbecue, bbq, case-substring:BBQ, not:charter pack, not:transit log, not:comfort pack', null),
       (20, 'Coffee Machine', 'coffee-machine', 'coffee, coffee machine, not:charter pack, not:transit log, not:comfort pack', null),
       (21, 'Fishing equipment', 'fishing-equipment', 'fishing equipment, not:charter pack, not:transit log, not:comfort pack', null),
       (22, 'Underwater scooter', 'underwater-scooter', 'underwater scooter, not:charter pack, not:transit log, not:comfort pack', null),
       (23, 'Family pack', 'family-pack', 'family pack, not:charter pack, not:transit log, not:comfort pack', null),
       (24, 'Adrenalin Pack', 'adrenalin-pack', 'adrenalin pack, not:charter pack, not:transit log, not:comfort pack', null),
       (25, 'APA (advance provisioning allowance)', 'apa', 'case:APA, case-substring:APA, advance provisioning allowance, not:charter pack, not:transit log, not:comfort pack', null),
       (26, 'Permit for Montenegro', 'permit-for-montenegro', 'permit for montenegro, not:charter pack, not:transit log, not:comfort pack', null),
       (27, 'Inflatable lifejacket', 'inflatable-lifejacket', 'inflatable lifejacket, not:charter pack, not:transit log, not:comfort pack', null),
       (28, 'Donut', 'donut', 'donut, not:charter pack, not:transit log, not:comfort pack', null),
       (29, 'Water skies', 'water-skies', 'water skies, water ski, token-match:water skis, waterskis, not:charter pack, not:transit log, not:comfort pack', null),
       (30, 'Larger RIB / dinghy', 'larger-rib', 'larger rib, dinghy, not:charter pack, not:transit log, not:comfort pack', null),
       (31, 'Snorkeling equipment', 'snorkeling-equipment', 'snorkeling equipment, not:charter pack, not:transit log, not:comfort pack', null),
       (32, 'Wakeboard', 'wakeboard', 'wakeboard, not:charter pack, not:transit log, not:comfort pack', null),
       (33, 'Seabob', 'seabob', 'seabob, not:charter pack, not:transit log, not:comfort pack', null),
       (34, 'Water tube', 'water-tube', 'water tube, not:charter pack, not:transit log, not:comfort pack', null),
       (35, 'Mono skis', 'mono-skis', 'mono skis, not:charter pack, not:transit log, not:comfort pack', null),
       (36, 'Kneeboard', 'kneeboard', 'kneeboard, not:charter pack, not:transit log, not:comfort pack', null),
       (37, 'Floating mats', 'floating-mats', 'floating mats, inflatable carpet, not:charter pack, not:transit log, not:comfort pack', null),
       (38, 'Banana boat', 'banana-boat', 'banana boat, not:charter pack, not:transit log, not:comfort pack', null),
       (39, 'Towing air tube ring', 'towing-air-tube-ring', 'towing air tube ring, not:charter pack, not:transit log, not:comfort pack', null),
       (40, 'Diving equipment', 'diving-equipment', 'diving equipment, token-match:diving, not:charter pack, not:transit log, not:comfort pack', null),
       (41, 'Subwing', 'subwing', 'subwing, not:charter pack, not:transit log, not:comfort pack', null),
       (42, 'Inflatable swimming platform', 'inflatable-swimming-platform', 'inflatable swimming platform, not:charter pack, not:transit log, not:comfort pack', null),
       (43, 'Jet ski', 'jet-ski', 'jet ski, not:charter pack, not:transit log, not:comfort pack', null),
       (44, 'eFoil', 'efoil', 'efoil, token-match:efoil, not:charter pack, not:transit log, not:comfort pack', null),
       (45, 'Airstream Towable', 'airstream-towable', 'airstream towable, not:charter pack, not:transit log, not:comfort pack', null)
ON CONFLICT (id)
    DO UPDATE SET name         = EXCLUDED.name,
                  label_code   = EXCLUDED.label_code,
                  match_keys   = EXCLUDED.match_keys,
                  filter_order = EXCLUDED.filter_order
;