INSERT INTO equipment (id, name, label_code, match_keys, category, filter_order)
VALUES (1, 'Air conditioning', 'air-conditioning', 'air conditioning, a/c, air condition', 0, 200),
       (2, 'Coffee machine', 'coffee-machine', 'token-match:coffee, coffee machine', 0, 201),
       (3, 'Cooker', 'cooker', 'token-match:cooker', 0, 203),
       (4, 'Dishwasher', 'dishwasher', 'dishwasher', 0, null),
       (5, 'Freezer', 'freezer', 'freezer', 0, null),
       (6, 'BBQ', 'BBQ', 'bbq, token-match:barbecue', 0, null),
       (7, 'Heating', 'heating', 'heating', 0, null),
       (8, 'Ice maker', 'ice-maker', 'ice maker', 0, null),
       (9, 'Kitchen utensils', 'kitchen-utensils', 'kitchen utensils, token-match:kitchen utensils', 0, 204),
       (10, 'Microwave', 'microwave', 'microwave', 0, null),
       (11, 'Outside shower', 'outside-shower', 'outside shower', 0, 202),
       (12, 'Oven', 'oven', 'token-match:oven', 0, 205),
       (13, 'Pillows and blankets', 'pillows-and-blankets', 'pillows and blankets, pillows, blankets', 0, null),
       (14, 'Fridge', 'fridge', 'token-match:fridge', 0, 206),
       (15, 'Shower', 'shower', 'token-match:shower, not:no inside shower', 0, null),
       (16, 'Sink', 'sink', 'sink', 0, null),
       (17, 'Towels', 'towels', 'towels, token-match:towels', 0, 207),
       (18, 'Washing machine', 'washing-machine', 'washing machine', 0, null),
       (19, 'Waste tank', 'waste-tank', 'waste tank', 0, 208),
       (20, 'Water maker', 'water-maker', 'water maker', 0, null),
       (21, 'Autopilot', 'autopilot', 'autopilot, not:no autopilot', 1, 100),
       (22, 'Bimini', 'bimini', 'token-match:bimini', 1, 103),
       (23, 'Bow thruster', 'bow-thruster', 'bow thruster', 1, null),
       (24, 'Salon GPS plotter', 'salon-GPS-plotter', 'salon GPS plotter, GPS plotter cabina', 1, null),
       (25, 'Outside GPS plotter', 'outside-GPS-plotter', 'outside GPS plotter', 1, 101),
       (26, 'Dinghy', 'dinghy', 'dinghy,dinghy outboard engine', 1, 104),
       (27, 'Electric winches', 'electric-winches', 'electric winches', 1, 105),
       (28, 'Flybridge', 'flybridge', 'flybridge', 1, null),
       (29, 'Generator', 'generator', 'generator', 1, 102),
       (30, 'Gennaker', 'gennaker', 'gennaker', 1, null),
       (31, 'Inverter', 'inverter', 'inverter', 1, null),
       (32, 'Radar', 'radar', 'radar', 1, null),
       (33, 'Safety net', 'safety-net', 'railing net,safety net,railing net safety', 1, null),
       (34, 'Solar panels', 'solar-panels', 'solar panels', 1, null),
       (35, 'Spinnaker', 'spinnaker', 'spinnaker', 1, null),
       (36, 'Teak deck', 'teak-deck', 'teak deck', 1, null),
       (37, 'Bathing platform', 'bathing-platform', 'bathing platform', 2, null),
       (38, 'Bicycle', 'bicycle', 'bicycle', 2, null),
       (39, 'DVD Player', 'DVD-player', 'dvd player', 2, null),
       (40, 'Fishing set', 'fishing-set', 'fishing set', 2, null),
       (41, 'Game console', 'game-console', 'game console', 2, null),
       (42, 'Inside speakers', 'inside-speakers', 'inside speakers', 2, null),
       (43, 'Jacuzzi', 'jacuzzi', 'jacuzzi', 2, null),
       (44, 'Jet ski', 'jet-ski', 'jet ski', 2, null),
       (45, 'Karaoke', 'karaoke', 'token-match:karaoke', 2, null),
       (46, 'Kayak', 'kayak', 'token-match:kayak', 2, null),
       (47, 'Flat screen TV', 'flat-screen-TV', 'flat screen tv, case-substring:TV', 2, null),
       (48, 'Outside speakers', 'outside-speakers', 'outside speakers', 2, 301),
       (49, 'Audio system', 'audio-system', 'audio system', 2, 303),
       (50, 'Snorkel sets', 'snorkel-sets', 'snorkel sets', 2, 302),
       (51, 'Stand Up Paddle', 'stand-up-paddle', 'case-substring:SUP, full-match:SUP, case:SUP, stand up paddle', 2, null),
       (52, 'Sun pads', 'sun-pads', 'sun pads', 2, null),
       (53, 'Surf', 'surf', 'surf, surf board', 2, null),
       (54, 'Wakeboard', 'wakeboard', 'wakeboard', 2, null),
       (55, 'Water skis', 'water-skis', 'water skis', 2, null),
       (56, 'Water toys', 'water-toys', 'water toys', 2, 300),
       (57, 'Windsurf', 'windsurf', 'windsurf', 2, null)
ON CONFLICT (id)
    DO UPDATE SET name         = EXCLUDED.name,
                  label_code   = EXCLUDED.label_code,
                  match_keys   = EXCLUDED.match_keys,
                  filter_order = EXCLUDED.filter_order
;