INSERT INTO equipment (id, name, label_code, match_keys, category, filter_order)
VALUES (1, 'Air conditioning', 'air-conditioning', 'air conditioning, a/c, air condition', 'SALOON_AND_CABINS',200),
       (2, 'Coffee machine', 'coffee-machine', 'token-match:coffee, coffee machine', 'SALOON_AND_CABINS',201),
       (3, 'Cooker', 'cooker', 'token-match:cooker', 'SALOON_AND_CABINS',203),
       (4, 'Dishwasher', 'dishwasher', 'dishwasher', 'SALOON_AND_CABINS',null),
       (5, 'Freezer', 'freezer', 'freezer', 'SALOON_AND_CABINS',null),
       (6, 'BBQ', 'BBQ', 'bbq, token-match:barbecue', 'SALOON_AND_CABINS',null),
       (7, 'Heating', 'heating', 'heating', 'SALOON_AND_CABINS',null),
       (8, 'Ice maker', 'ice-maker', 'ice maker', 'SALOON_AND_CABINS',null),
       (9, 'Kitchen utensils', 'kitchen-utensils', 'kitchen utensils, token-match:kitchen utensils', 'SALOON_AND_CABINS',204),
       (10, 'Microwave', 'microwave', 'microwave', 'SALOON_AND_CABINS',null),
       (11, 'Outside shower', 'outside-shower', 'outside shower', 'SALOON_AND_CABINS',202),
       (12, 'Oven', 'oven', 'token-match:oven', 'SALOON_AND_CABINS',205),
       (13, 'Pillows and blankets', 'pillows-and-blankets', 'pillows and blankets, pillows, blankets', 'SALOON_AND_CABINS',null),
       (14, 'Fridge', 'fridge', 'token-match:fridge', 'SALOON_AND_CABINS',206),
       (15, 'Shower', 'shower', 'token-match:shower, not:no inside shower', 'SALOON_AND_CABINS',null),
       (16, 'Sink', 'sink', 'sink', 'SALOON_AND_CABINS',null),
       (17, 'Towels', 'towels', 'towels, token-match:towels', 'SALOON_AND_CABINS',207),
       (18, 'Washing machine', 'washing-machine', 'washing machine', 'SALOON_AND_CABINS',null),
       (19, 'Waste tank', 'waste-tank', 'waste tank, holding tank, not:water maker, not:watermaker, not:desalin', 'SALOON_AND_CABINS',208),
       (20, 'Water maker', 'water-maker', 'token-match:water maker, token-match:watermaker, token-match:desalinator', 'SALOON_AND_CABINS',210),
       (21, 'Autopilot', 'autopilot', 'autopilot, not:no autopilot', 'NAVIGATION_AND_SAFETY',100),
       (22, 'Bimini', 'bimini', 'token-match:bimini', 'NAVIGATION_AND_SAFETY',103),
       (23, 'Bow thruster', 'bow-thruster', 'bow thruster', 'NAVIGATION_AND_SAFETY',null),
       (24, 'Salon GPS plotter', 'salon-GPS-plotter', 'salon GPS plotter, GPS plotter cabina', 'NAVIGATION_AND_SAFETY',null),
       (25, 'Outside GPS plotter', 'outside-GPS-plotter', 'outside GPS plotter', 'NAVIGATION_AND_SAFETY',101),
       (26, 'Dinghy', 'dinghy', 'dinghy,dinghy outboard engine', 'NAVIGATION_AND_SAFETY',104),
       (27, 'Electric winches', 'electric-winches', 'electric winches', 'NAVIGATION_AND_SAFETY',105),
       (28, 'Flybridge', 'flybridge', 'flybridge', 'NAVIGATION_AND_SAFETY',null),
       (29, 'Generator', 'generator', 'generator', 'NAVIGATION_AND_SAFETY',102),
       (30, 'Gennaker', 'gennaker', 'gennaker', 'NAVIGATION_AND_SAFETY',null),
       (31, 'Inverter', 'inverter', 'inverter', 'NAVIGATION_AND_SAFETY',null),
       (32, 'Radar', 'radar', 'radar', 'NAVIGATION_AND_SAFETY',null),
       (33, 'Safety net', 'safety-net', 'railing net,safety net,railing net safety', 'NAVIGATION_AND_SAFETY',null),
       (34, 'Solar panels', 'solar-panels', 'solar panels', 'NAVIGATION_AND_SAFETY',null),
       (35, 'Spinnaker', 'spinnaker', 'spinnaker', 'NAVIGATION_AND_SAFETY',null),
       (36, 'Teak deck', 'teak-deck', 'teak deck', 'NAVIGATION_AND_SAFETY',null),
       (37, 'Bathing platform', 'bathing-platform', 'bathing platform', 'ENTERTAINMENT',null),
       (38, 'Bicycle', 'bicycle', 'bicycle', 'ENTERTAINMENT',null),
       (39, 'DVD Player', 'DVD-player', 'dvd player', 'ENTERTAINMENT',null),
       (40, 'Fishing set', 'fishing-set', 'fishing set', 'ENTERTAINMENT',null),
       (41, 'Game console', 'game-console', 'game console', 'ENTERTAINMENT',null),
       (42, 'Inside speakers', 'inside-speakers', 'inside speakers', 'ENTERTAINMENT',null),
       (43, 'Jacuzzi', 'jacuzzi', 'jacuzzi', 'ENTERTAINMENT',null),
       (44, 'Jet ski', 'jet-ski', 'jet ski', 'ENTERTAINMENT',null),
       (45, 'Karaoke', 'karaoke', 'token-match:karaoke', 'ENTERTAINMENT',null),
       (46, 'Kayak', 'kayak', 'token-match:kayak', 'ENTERTAINMENT',null),
       (47, 'Flat screen TV', 'flat-screen-TV', 'flat screen tv, case-substring:TV', 'ENTERTAINMENT',null),
       (48, 'Outside speakers', 'outside-speakers', 'outside speakers', 'ENTERTAINMENT',301),
       (49, 'Audio system', 'audio-system', 'audio system', 'ENTERTAINMENT',303),
       (50, 'Snorkel sets', 'snorkel-sets', 'snorkel sets', 'ENTERTAINMENT',302),
       (51, 'Stand Up Paddle', 'stand-up-paddle', 'case-substring:SUP, full-match:SUP, case:SUP, stand up paddle', 'ENTERTAINMENT',null),
       (52, 'Sun pads', 'sun-pads', 'sun pads', 'ENTERTAINMENT',null),
       (53, 'Surf', 'surf', 'surf, surf board', 'ENTERTAINMENT',null),
       (54, 'Wakeboard', 'wakeboard', 'wakeboard', 'ENTERTAINMENT',null),
       (55, 'Water skis', 'water-skis', 'water skis', 'ENTERTAINMENT',null),
       (56, 'Water toys', 'water-toys', 'water toys', 'ENTERTAINMENT',300),
       (57, 'Windsurf', 'windsurf', 'windsurf', 'ENTERTAINMENT',null),
       (58, 'WiFi', 'wifi', 'wi-fi, wifi, case-substring:WIFI, case-substring:WI-FI', 'SALOON_AND_CABINS',209)
ON CONFLICT (id)
    DO UPDATE SET name         = EXCLUDED.name,
                  label_code   = EXCLUDED.label_code,
                  match_keys   = EXCLUDED.match_keys,
                  filter_order = EXCLUDED.filter_order
;