create sequence revinfo_seq increment by 50;

create table if not exists revinfo
(
    id integer generated by default as identity,
    timestamp bigint,
    modifier_user_id bigint,
    primary key (id)
);

create table if not exists role_assignments_revisions
(
    id bigserial not null,
    user_id bigint,
    role_id bigint,

    creator_id bigint,
    modifier_id bigint,
    created timestamp,
    modified timestamp,
    entity_status varchar(31),

    rev integer not null,
    revtype smallint,
    primary key (rev, id),
    constraint fk_role_assignments_rev foreign key(rev)
        references revinfo(id)
);

CREATE POLICY app_user ON public.revinfo
	AS PERMISSIVE
	FOR ALL
	TO boat4you_app;

CREATE POLICY app_user ON public.role_assignments_revisions
	AS PERMISSIVE
	FOR ALL
	TO boat4you_app;

GRANT SELECT ON revinfo_seq TO boat4you_app;