UPDATE region SET country_id = 40, country_code = 'CA' WHERE id = 119; -- Canada/BritishColumbia-PacificCoast
UPDATE region SET country_id = 40, country_code = 'CA' WHERE id = 120; -- Canada/Ontario-RideauCanal
UPDATE region SET country_id = 101, country_code = 'HU' WHERE id = 123; -- Tokaj
UPDATE region SET country_id = 101, country_code = 'HU' WHERE id = 124; -- Tisza
UPDATE region SET country_id = 178, country_code = 'PT' WHERE id = 125; -- Evora/GreatLake
UPDATE region SET country_id = 83, country_code = 'DE' WHERE id = 129; -- SaaleValley
UPDATE region SET country_id = 83, country_code = 'DE' WHERE id = 130; -- MecklenburgLakes
UPDATE region SET country_id = 110, country_code = 'IT' WHERE id = 126; -- VeniceLagoon
UPDATE region SET country_id = 110, country_code = 'IT' WHERE id = 143; -- GulfofTaranto
UPDATE region SET country_id = 110, country_code = 'IT' WHERE id = 180; -- Liguria/Toscana
UPDATE region SET country_id = 110, country_code = 'IT' WHERE id = 182; -- ItalianAdriatic
UPDATE region SET country_id = 156, country_code = 'NL' WHERE id = 127; -- Gelderland
UPDATE region SET country_id = 156, country_code = 'NL' WHERE id = 128; -- NorthHolland/Amsterdam
UPDATE region SET country_id = 156, country_code = 'NL' WHERE id = 147; -- Zeeland
UPDATE region SET country_id = 156, country_code = 'NL' WHERE id = 148; -- Ijsselmeer&Markermeer
UPDATE region SET country_id = 31, country_code = 'BR' WHERE id = 150; -- RiodeJaneiro
UPDATE region SET country_id = 209, country_code = 'ES' WHERE id = 140; -- Menorca
UPDATE region SET country_id = 209, country_code = 'ES' WHERE id = 141; -- Mallorca
UPDATE region SET country_id = 209, country_code = 'ES' WHERE id = 142; -- Ibiza
UPDATE region SET country_id = 209, country_code = 'ES' WHERE id = 151; -- Galicia
UPDATE region SET country_id = 209, country_code = 'ES' WHERE id = 152; -- Murcia
UPDATE region SET country_id = 209, country_code = 'ES' WHERE id = 156; -- Valencia
UPDATE region SET country_id = 236, country_code = 'US' WHERE id = 158; -- EasternSeaboard
UPDATE region SET country_id = 37, country_code = 'CV' WHERE id = 159; -- CapeVerde
UPDATE region SET country_id = 76, country_code = 'FR' WHERE id = 131; -- LotValley
UPDATE region SET country_id = 76, country_code = 'FR' WHERE id = 133; -- Anjou
UPDATE region SET country_id = 76, country_code = 'FR' WHERE id = 134; -- Charente
UPDATE region SET country_id = 76, country_code = 'FR' WHERE id = 135; -- Camargue
UPDATE region SET country_id = 76, country_code = 'FR' WHERE id = 136; -- CanalduMidi
UPDATE region SET country_id = 76, country_code = 'FR' WHERE id = 137; -- Bretagne
UPDATE region SET country_id = 76, country_code = 'FR' WHERE id = 138; -- BourgogneetSaône
UPDATE region SET country_id = 76, country_code = 'FR' WHERE id = 183; -- Normandy/Bretagne
UPDATE region SET country_id = 76, country_code = 'FR' WHERE id = 184; -- FrenchRiviera(Côted'Azur)
UPDATE region SET country_id = 230, country_code = 'TR' WHERE id = 154; -- Izmir
UPDATE region SET country_id = 230, country_code = 'TR' WHERE id = 155; -- Istanbul/Bosphorus
UPDATE region SET country_id = 230, country_code = 'TR' WHERE id = 174; -- Marmaris/Fethiye/Gocek
UPDATE region SET country_id = 230, country_code = 'TR' WHERE id = 175; -- Bodrum
UPDATE region SET country_id = 234, country_code = 'GB' WHERE id = 176; -- Scotland
UPDATE region SET country_id = 234, country_code = 'GB' WHERE id = 177; -- Solent
UPDATE region SET country_id = 86, country_code = 'GR' WHERE id = 149; -- SouthPeloponnese
UPDATE region SET country_id = 86, country_code = 'GR' WHERE id = 157; -- NorthEastAegean
UPDATE region SET country_id = 86, country_code = 'GR' WHERE id = 165; -- Athens/SaronicGulf
UPDATE region SET country_id = 86, country_code = 'GR' WHERE id = 186; -- Sporades
UPDATE region SET country_id = 86, country_code = 'GR' WHERE id = 187; -- Ionian
UPDATE region SET country_id = 54, country_code = 'HR' WHERE id = 189; -- Split
UPDATE region SET country_id = 54, country_code = 'HR' WHERE id = 190; -- Kornati
UPDATE region SET country_id = 54, country_code = 'HR' WHERE id = 191; -- Šibenik
UPDATE region SET country_id = 54, country_code = 'HR' WHERE id = 192; -- Zadar
UPDATE region SET country_id = 54, country_code = 'HR' WHERE id = 193; -- Istria/Kvarner